#!/usr/bin/env bash

# Check if rofi and jq are available
if ! command -v rofi &> /dev/null || ! command -v jq &> /dev/null; then
    if command -v notify-send &> /dev/null; then
        notify-send "Error" "rofi or jq not found"
    fi
    exit 1
fi

# Get monitor information in JSON format
monitors_json=$(hyprctl monitors -j)

# Get active/focused monitor name
monitor_name=$(echo "$monitors_json" | jq -r '.[] | select(.focused == true) | .name')
if [ -z "$monitor_name" ] || [ "$monitor_name" = "null" ]; then
    monitor_name=$(echo "$monitors_json" | jq -r '.[0].name')
fi

if [ -z "$monitor_name" ] || [ "$monitor_name" = "null" ]; then
    exit 1
fi

# Get current scale of the monitor
current_scale=$(echo "$monitors_json" | jq -r ".[] | select(.name == \"$monitor_name\") | .scale")
if [ -z "$current_scale" ] || [ "$current_scale" = "null" ]; then
    current_scale=1
fi

# Extract available modes for this monitor
available_modes=$(echo "$monitors_json" | jq -r ".[] | select(.name == \"$monitor_name\") | .availableModes[]")

if [ -z "$available_modes" ]; then
    exit 1
fi

# Use rofi to select a resolution
selected_mode=$(echo "$available_modes" | rofi -dmenu -i -p "Select resolution for $monitor_name")

if [ -n "$selected_mode" ]; then
    # Strip "Hz" if present
    clean_mode=${selected_mode%Hz}
    
    # Apply resolution via hyprctl eval
    hyprctl eval "hl.monitor({output = '$monitor_name', mode = '$clean_mode', position = 'auto', scale = $current_scale})"
    
    # Save the configuration to monitors.lua to survive Hyprland configuration reloads (e.g. on wallpaper changes)
    cat <<EOF > "$HOME/.config/hypr/monitors.lua"
-------------------------------------------------------
-- Monitor Setup (Auto-generated by select-resolution.sh)
-------------------------------------------------------

hl.monitor({
    output = "$monitor_name",
    mode = "$clean_mode",
    position = "auto",
    scale = $current_scale
})
EOF
    
    # Notify the user
    if command -v notify-send &> /dev/null; then
        notify-send "Monitor Config" "Set $monitor_name to $clean_mode (Scale: $current_scale)"
    fi
fi
